version: "3.8"
services:
  redis:
    image: redis:6.2-alpine
    container_name: rdb
    restart: always
    ports:
      - "6379:6379"
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: rdb-insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - rdb-insight-volume-data:/db
  node_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: node-server
    restart: always
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
volumes:
  rdb-volume-data:
  rdb-insight-volume-data:
